zpb_admin_animations_days_list:
    path: /
    defaults: { _controller: ZPBAdminBundle:Animation/Day:list }
    methods: ["GET"]

zpb_admin_animations_days_create:
    path: /nouvelle
    defaults: { _controller: ZPBAdminBundle:Animation/Day:create }
    methods: ["GET","POST"]

zpb_admin_animations_days_update:
    path: /modifier/{id}
    defaults: { _controller: ZPBAdminBundle:Animation/Day:update }
    methods: ["GET","POST"]

zpb_admin_animations_days_delete:
    path: /supprimer/{id}
    defaults: { _controller: ZPBAdminBundle:Animation/Day:delete }
    methods: ["GET"]

zpb_admin_animations_days_hour_change:
    path: /horaire/change/heure
    defaults: { _controller: ZPBAdminBundle:Animation/Day:xhrScheduleChangeHour }
    methods: ["POST"]

zpb_admin_animations_days_min_change:
    path: /horaire/change/minute
    defaults: { _controller: ZPBAdminBundle:Animation/Day:xhrScheduleChangeMin }
    methods: ["POST"]

zpb_admin_animations_days_add_schedule:
    path: /ajouter/horaire
    defaults: { _controller: ZPBAdminBundle:Animation/Day:xhrAddScheduleToDay }
    methods: ["POST"]
