zpb_admin_animations_list:
    path: /
    defaults: { _controller: ZPBAdminBundle:Animation/Animation:list }
    methods: ["GET"]

zpb_admin_animations_create:
    path: /nouvelle
    defaults: { _controller: ZPBAdminBundle:Animation/Animation:create }
    methods: ["GET","POST"]

zpb_admin_animations_update:
    path: /modifier/{id}
    defaults: { _controller: ZPBAdminBundle:Animation/Animation:update }
    methods: ["GET","POST"]

zpb_admin_animations_delete:
    path: /supprimer/{id}
    defaults: { _controller: ZPBAdminBundle:Animation/Animation:delete }
    methods: ["GET"]



zpb_admin_animations_planning_management:
    path: /planning
    defaults: { _controller: ZPBAdminBundle:Animation/Planning:index }
    methods: ["GET"]

zpb_admin_animations_planning_api_get_days_in_month:
    path: /api/days/{year}/{month}
    defaults: { _controller: ZPBAdminBundle:Animation/Planning:apiGetDaysInMonth }
    methods: ["GET"]
    requirements:
        year: "20(0[0-9]|[1-9][0-9])"
        month: "[1-9]|1[0-2]"
