zpb_admin_photos_list:
    path: /liste/categorie/{id}
    defaults: { _controller: ZPBAdminBundle:General/Photo:list }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_photos_choose_list:
    path: /choix_liste
    defaults: { _controller: ZPBAdminBundle:General/Photo:chooseList }
    methods: ["GET"]

zpb_admin_photos_choose_institution:
    path: /choix-institution
    defaults: { _controller: ZPBAdminBundle:General/Photo:chooseInstitution }
    methods: ["GET"]

zpb_admin_photos_create:
    path: /nouvelle/{institution_slug}
    defaults: { _controller: ZPBAdminBundle:General/Photo:create }
    methods: ["GET", "POST"]
    requirements:
        institution_slug: "^[a-zA-Z0-9_-]+$"

zpb_admin_photos_update:
    path: /modifier/{id}
    defaults: { _controller: ZPBAdminBundle:General/Photo:update }
    methods: ["GET", "POST"]
    requirements:
        id: \d+

zpb_admin_photos_delete:
    path: /supprimer/{id}
    defaults: { _controller: ZPBAdminBundle:General/Photo:delete }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_photos_position_up:
    path: /position/remonter/{id}
    defaults: { _controller: ZPBAdminBundle:General/Photo:positionUp }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_photos_position_down:
    path: /position/descendre/{id}
    defaults: { _controller: ZPBAdminBundle:General/Photo:positionDown }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_photos_position_xhr_change:
    path: /xhr/position/modifier
    defaults: { _controller: ZPBAdminBundle:General/Photo:positionChangeXhr }
    methods: ["POST"]
