zpb_admin_photos_hd_choose_list:
    path: /choix_liste
    defaults: { _controller: ZPBAdminBundle:General/PhotoHd:chooseList }
    methods: ["GET"]

zpb_admin_photos_hd_list:
    path: /liste/categorie/{id}
    defaults: { _controller: ZPBAdminBundle:General/PhotoHd:list }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_photos_hd_choose_institution:
    path: /choix-institution
    defaults: { _controller: ZPBAdminBundle:General/PhotoHd:chooseInstitution }
    methods: ["GET"]

zpb_admin_photos_hd_create:
    path: /nouvelle/{institution_slug}
    defaults: { _controller: ZPBAdminBundle:General/PhotoHd:create }
    methods: ["GET", "POST"]
    requirements:
        institution_slug: "^[a-zA-Z0-9_-]+$"




zpb_admin_photos_hd_position_xhr_change:
    path: /xhr/position/modifier
    defaults: { _controller: ZPBAdminBundle:General/PhotoHd:positionChangeXhr }
    methods: ["POST"]




zpb_admin_photos_hd_update:
    path: /mise-a-jour/{id}
    defaults: { _controller: ZPBAdminBundle:General/PhotoHd:update }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_photos_hd_delete:
    path: /supprimer/{id}
    defaults: { _controller: ZPBAdminBundle:General/PhotoHd:delete }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_photos_hd_delete_users_list:
    path: /utilisateurs/liste
    defaults: { _controller: ZPBAdminBundle:General/PhotoHd:listUsers }
    methods: ["GET"]

zpb_admin_photos_hd_delete_users_create:
    path: /utilisateurs/nouveau
    defaults: { _controller: ZPBAdminBundle:General/PhotoHd:createUser }
    methods: ["GET", "POST"]

zpb_admin_photos_hd_delete_users_update:
    path: /utilisateurs/modifier/{id}
    defaults: { _controller: ZPBAdminBundle:General/PhotoHd:updateUser }
    methods: ["GET","POST"]
    requirements:
        id: \d+

zpb_admin_photos_hd_delete_users_delete:
    path: /utilisateurs/supprimer/{id}
    defaults: { _controller: ZPBAdminBundle:General/PhotoHd:deleteUser }
    methods: ["GET"]
    requirements:
        id: \d+



