zpb_admin_actualites_list:
    path: /liste/brouillons
    defaults: { _controller: ZPBAdminBundle:General/Post:list }
    methods: ["GET"]

zpb_admin_actualites_list_published:
    path: /liste/publications
    defaults: { _controller: ZPBAdminBundle:General/Post:listPublished }
    methods: ["GET"]

zpb_admin_actualites_list_archived:
    path: /liste/archives
    defaults: { _controller: ZPBAdminBundle:General/Post:listArchived }
    methods: ["GET"]

zpb_admin_actualites_create:
    path: /nouveau
    defaults: { _controller: ZPBAdminBundle:General/Post:create }
    methods: ["GET","POST"]

zpb_admin_actualites_delete:
    path: /supprimer/{id}
    defaults: { _controller: ZPBAdminBundle:General/Post:delete }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_actualites_update_draft:
    path: /modifier/brouillon/{id}
    defaults: { _controller: ZPBAdminBundle:General/Post:updateDraft }
    methods: ["GET","POST"]
    requirements:
        id: \d+

zpb_admin_actualites_update_published:
    path: /modifier/article-publie/{id}
    defaults: { _controller: ZPBAdminBundle:General/Post:updatePublished }
    methods: ["GET","POST"]
    requirements:
        id: \d+

zpb_admin_actualites_update_archived:
    path: /modifier/article-archive/{id}
    defaults: { _controller: ZPBAdminBundle:General/Post:updateArchived }
    methods: ["GET","POST"]
    requirements:
        id: \d+


zpb_admin_actualites_update_publication:
    path: /modifier/publication/{id}
    defaults: { _controller: ZPBAdminBundle:General/Post:updatePublication }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_actualites_publier:
    path: /publier/{id}
    defaults: { _controller: ZPBAdminBundle:General/Post:publish }
    methods: ["GET"]
    requirements:
        id: \d+


zpb_admin_actualite_img_upload:
    path: /image/upload
    defaults: { _controller: ZPBAdminBundle:General/Post:postImageUpload }
    methods: ["POST"]

########### api routes
zpb_admin_actualites_api_post_categorie:
    path: /api/post/categories
    defaults: { _controller: ZPBAdminBundle:General/Post:apiCategoryCreate }
    methods: ["POST"]


zpb_admin_actualites_api_post_tag:
    path: /api/post/tags
    defaults: { _controller: ZPBAdminBundle:General/Post:apiTagCreate }
    methods: ["POST"]

zpb_admin_actualites_api_post_save:
    path: /api/post
    defaults: { _controller: ZPBAdminBundle:General/Post:apiPublishPost }
    methods: ["POST"]

















