zpb_admin_actualites_list:
    path: /liste/brouillons
    defaults: { _controller: ZPBAdminBundle:General/Post:list }
    methods: ["GET"]

zpb_admin_actualites_list_published:
    path: /liste/publications
    defaults: { _controller: ZPBAdminBundle:General/Post:listPublished }
    methods: ["GET"]

zpb_admin_actualites_list_archived:
    path: /liste/archives
    defaults: { _controller: ZPBAdminBundle:General/Post:listArchived }
    methods: ["GET"]

zpb_admin_actualites_create:
    path: /nouveau
    defaults: { _controller: ZPBAdminBundle:General/Post:create }
    methods: ["GET","POST"]

zpb_admin_actualites_publier:
    path: /publier/{id}
    defaults: { _controller: ZPBAdminBundle:General/Post:publish }
    methods: ["GET"]
    requirements:
        id: \d+




########### api routes
zpb_admin_actualites_api_post_categorie:
    path: /api/post/categories
    defaults: { _controller: ZPBAdminBundle:General/Post:apiCategoryCreate }
    methods: ["POST"]


zpb_admin_actualites_api_post_tag:
    path: /api/post/tags
    defaults: { _controller: ZPBAdminBundle:General/Post:apiTagCreate }
    methods: ["POST"]


















