zpb_sites_zoo_actualites_list:
    path: /
    defaults: { _controller: ZPBAdminBundle:General/Post:list }
    methods: ["GET"]

zpb_sites_zoo_actualites_create:
    path: /nouveau
    defaults: { _controller: ZPBAdminBundle:General/Post:create }
    methods: ["GET","POST"]

zpb_sites_zoo_actualites_publier:
    path: /publier/{id}
    defaults: { _controller: ZPBAdminBundle:General/Post:publish }
    methods: ["GET"]
    requirements:
        id: \d+























