zpb_admin_posts_list:
    path: /
    defaults: { _controller: ZPBAdminBundle:General/Post:list }
    methods: ["GET"]

zpb_admin_posts_create:
    path: /ecrire
    defaults: { _controller: ZPBAdminBundle:General/Post:create }
    methods: ["GET","POST"]

zpb_admin_posts_update:
    path: /modifier/{id}
    defaults: { _controller: ZPBAdminBundle:General/Post:update }
    methods: ["GET","POST"]
    requirements:
        id: \d+

zpb_admin_posts_delete:
    path: /supprimer/{id}
    defaults: { _controller: ZPBAdminBundle:General/Post:delete }
    methods: ["GET"]
    requirements:
        id: \d+
