######################################################### crud AnimalSpecies
zpb_admin_sponsor_species_list:
   path: /especes/liste
   defaults: { _controller: ZPBAdminBundle:Parrainage/Species:list }
   methods: ["GET"]

zpb_admin_sponsor_species_create:
    path: /especes/nouvelle
    defaults: { _controller: ZPBAdminBundle:Parrainage/Species:create }
    methods: ["GET", "POST"]

zpb_admin_sponsor_species_update:
   path: /especes/modifier/{id}
   defaults: { _controller: ZPBAdminBundle:Parrainage/Species:update }
   methods: ["GET","POST"]
   requirements:
       id: \d+

zpb_admin_sponsor_species_delete:
    path: /especes/supprimer/{id}
    defaults: { _controller: ZPBAdminBundle:Parrainage/Species:delete }
    methods: ["GET"]
    requirements:
        id: \d+


######################################################### crud AnimalCategory
zpb_admin_sponsor_animals_categories_list:
   path: /categories-animaux/liste
   defaults: { _controller: ZPBAdminBundle:Parrainage/Category:list }
   methods: ["GET"]

zpb_admin_sponsor_animals_categories_create:
    path: /categories-animaux/nouvelle
    defaults: { _controller: ZPBAdminBundle:Parrainage/Category:create }
    methods: ["GET", "POST"]

zpb_admin_sponsor_animals_categories_update:
   path: /categories-animaux/modifier/{id}
   defaults: { _controller: ZPBAdminBundle:Parrainage/Category:update }
   methods: ["GET","POST"]
   requirements:
       id: \d+

zpb_admin_sponsor_animals_categories_delete:
    path: /categories-animaux/supprimer/{id}
    defaults: { _controller: ZPBAdminBundle:Parrainage/Category:delete }
    methods: ["GET"]
    requirements:
        id: \d+


######################################################### XHR AnimalCategory
zpb_admin_sponsor_animals_xhr_update_category:
    path: /xhr/modifier/animal-categorie
    defaults: { _controller: ZPBAdminBundle:Parrainage/XHR:animalChangeCategory }
    methods: ["POST"]



######################################################### crud Animal
zpb_admin_sponsor_animals_list:
   path: /animaux/liste
   defaults: { _controller: ZPBAdminBundle:Parrainage/Animal:list }
   methods: ["GET"]

zpb_admin_sponsor_animals_create:
    path: /animaux/nouveau
    defaults: { _controller: ZPBAdminBundle:Parrainage/Animal:create }
    methods: ["GET", "POST"]

zpb_admin_sponsor_animals_update:
   path: /animaux/modifier/{id}
   defaults: { _controller: ZPBAdminBundle:Parrainage/Animal:update }
   methods: ["GET","POST"]
   requirements:
       id: \d+

zpb_admin_sponsor_animals_delete:
    path: /animaux/supprimer/{id}
    defaults: { _controller: ZPBAdminBundle:Parrainage/Animal:delete }
    methods: ["GET"]
    requirements:
        id: \d+

######################################################### Animals Images
zpb_admin_sponsor_animals_images:
    path: /animal/{id}/images
    defaults: { _controller: ZPBAdminBundle:Parrainage/AnimalImage:imagesByAnimal }
    methods: ["GET"]
    requirements:
       id: \d+

zpb_admin_sponsor_animals_add_xhr_hd_images:
    path: /xhr/animal/ajouter/hd-images
    defaults: { _controller: ZPBAdminBundle:Parrainage/AnimalImage:addHdXhr }
    methods: ["POST"]

zpb_admin_sponsor_animals_delete_xhr_hd_images:
    path: /xhr/animal/supprimer/hd-images/{id}
    defaults: { _controller: ZPBAdminBundle:Parrainage/AnimalImage:deleteHdXhr }
    methods: ["GET"]
    requirements:
        id: \d+


zpb_admin_sponsor_animals_add_xhr_front_images:
   path: /xhr/animal/ajouter/front-images
   defaults: { _controller: ZPBAdminBundle:Parrainage/AnimalImage:addFrontXhr }
   methods: ["POST"]

zpb_admin_sponsor_animals_delete_xhr_front_images:
    path: /xhr/animal/supprimer/front-images/{id}
    defaults: { _controller: ZPBAdminBundle:Parrainage/AnimalImage:deleteFrontXhr }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_sponsor_animals_add_xhr_wallpaper_images:
   path: /xhr/animal/ajouter/wallpaper-images
   defaults: { _controller: ZPBAdminBundle:Parrainage/AnimalImage:addWallpaperXhr }
   methods: ["POST"]

zpb_admin_sponsor_animals_delete_xhr_wallpaper_images:
    path: /xhr/animal/supprimer/wallpaper-images/{id}
    defaults: { _controller: ZPBAdminBundle:Parrainage/AnimalImage:deleteWallpaperXhr }
    methods: ["GET"]
    requirements:
        id: \d+


######################################################### Sponsorings
zpb_admin_sponsor_sponsorings_list:
   path: /formules/liste
   defaults: { _controller: ZPBAdminBundle:Parrainage/Sponsoring:list }
   methods: ["GET"]

zpb_admin_sponsor_sponsorings_create:
    path: /formules/nouveau
    defaults: { _controller: ZPBAdminBundle:Parrainage/Sponsoring:create }
    methods: ["GET", "POST"]

zpb_admin_sponsor_sponsorings_update:
   path: /formules/modifier/{id}
   defaults: { _controller: ZPBAdminBundle:Parrainage/Sponsoring:update }
   methods: ["GET","POST"]
   requirements:
       id: \d+

zpb_admin_sponsor_sponsorings_delete:
    path: /formules/supprimer/{id}
    defaults: { _controller: ZPBAdminBundle:Parrainage/Sponsoring:delete }
    methods: ["GET"]
    requirements:
        id: \d+



