zpb_admin_zoo_press_release_list:
    path: /
    defaults: { _controller: ZPBAdminBundle:Zoo/PressRelease:list}
    methods: ["GET"]



zpb_admin_zoo_press_release_create:
    path: /nouveau
    defaults: { _controller: ZPBAdminBundle:Zoo/PressRelease:create}
    methods: ["GET","POST"]




zpb_admin_zoo_press_release_update:
    path: /modifier/{id}
    defaults: { _controller: ZPBAdminBundle:Zoo/PressRelease:update}
    methods: ["GET","POST"]
    requirements:
        id: \d+



zpb_admin_zoo_press_release_delete:
    path: /supprimer/{id}
    defaults: { _controller: ZPBAdminBundle:Zoo/PressRelease:delete}
    methods: ["GET"]
    requirements:
        id: \d+


zpb_admin_xhr_upload_pdf:
   path: /upload/pdf
   defaults: { _controller: ZPBAdminBundle:General/XHR:uploadPdf }
   methods: ["POST"]

zpb_admin_xhr_update_com_pdf:
   path: /update/communique/pdf
   defaults: { _controller: ZPBAdminBundle:General/XHR:updateCommuniquePdf }
   methods: ["POST"]




















