zpb_admin_zoo_header_manager:
    path: /
    defaults: { _controller: ZPBAdminBundle:Zoo/Header:index }
    methods: ["GET"]

zpb_admin_zoo_header_manager_img_upload:
    path: /slider/{id}/image/upload
    defaults: { _controller: ZPBAdminBundle:Zoo/Header:xhrImageUpload }
    methods: ["POST"]
    requirements:
        id: \d+
zpb_admin_zoo_header_manager_img_position:
    path: /slider/{id}/image/position
    defaults: { _controller: ZPBAdminBundle:Zoo/Header:xhrUpdateImgPosition }
    methods: ["POST"]
    requirements:
        id: \d+
zpb_admin_zoo_header_manager_img_delete:
    path: /slider/{id}/image/delete
    defaults: { _controller: ZPBAdminBundle:Zoo/Header:xhrDeleteSlide }
    methods: ["GET"]
    requirements:
        id: \d+
zpb_admin_zoo_header_manager_img_activate:
    path: /slider/{id}/image/activate
    defaults: { _controller: ZPBAdminBundle:Zoo/Header:xhrActivateSlide }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_zoo_header_manager_img_desactivate:
    path: /slider/{id}/image/desactivate
    defaults: { _controller: ZPBAdminBundle:Zoo/Header:xhrDesActivateSlide }
    methods: ["GET"]
    requirements:
        id: \d+


