<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnimationDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimationDayRepository extends EntityRepository
{
    public function getByMonth($month, $year = 2014)
    {

    }
}
