<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnimationProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimationProgramRepository extends EntityRepository
{
    public function animationsInMonth($month, $year = 2014)
    {
        $dateStart = new \DateTime($year.'/'.$month.'/1 00:00:00');
        $nextMonth = $month+1;
        if($nextMonth>12){
            $nextMonth = 1;
            $year += 1;
        }
        $dateEnd = new \DateTime($year.'/'.$nextMonth.'/1 00:00:00');

        $qb = $this->createQueryBuilder('p')->where('p.daytime > :start')->andWhere('p.daytime < :end')->orderBy('p.daytime', 'ASC');
        $qb->setParameter('start', $dateStart);
        $qb->setParameter('end', $dateEnd);

        return $qb->getQuery()->getResult();
    }

    public function getAnimationsInMonth($month, $year = 2014)
    {
        $days = $this->animationsInMonth($month, $year);

        $result = ['year'=>$year, 'month'=>$month, 'days'=>[]];

        foreach($days as $day){

        }

    }
}
