<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnimationProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimationProgramRepository extends EntityRepository
{
    public function animationsInMonth($month, $year = 2014)
    {

        $m = \DateTime::createFromFormat('j/n/Y', '1/'.$month.'/'.$year);
        $daysInMonth = (int)$m->format('t') + 1;
        $result = [];
        for($i = 1; $i < $daysInMonth; $i++){
            $d = \DateTime::createFromFormat('Y/n/j',$year.'/'.$month.'/'.$i);
            $qb = $this->createQueryBuilder('p')->where('p.daytime = :theDate')
                ->setParameter('theDate', $d, \Doctrine\DBAL\Types\Type::DATE);
            $result[] = $qb->getQuery()->getOneOrNullResult();
        }


        return $result;


    }

    public function getAnimationsInMonth($month, $year = 2014)
    {

        $programs = $this->animationsInMonth($month, $year);

        $result = ['error'=>false, 'message'=>'NO ERROR','year'=>$year, 'month'=>$month, 'days'=>[]];

        foreach($programs as $prog){

            if($prog != null){
                /** @var \ZPB\AdminBundle\Entity\AnimationProgram $prog */
                $days = $prog->getAnimationDays();

                $tmp = [];
                foreach($days as $day){
                    /** @var \ZPB\AdminBundle\Entity\AnimationDay $day */
                    $tmp[] = $day->toArray();
                }
                $result['days'][] = $tmp;
            } else {
                $result['days'][] = [];
            }

        }

        return $result;

    }
}
