<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FAQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FAQRepository extends EntityRepository
{
    public function findByHost($host)
    {
        $qb = $this->createQueryBuilder('f')
            ->join('ZPB\AdminBundle\Entity\Institution ', 'i')
            ->where('i.host=:host')

            ->setParameter('host', $host);


        return $qb->getQuery()->getResult();
    }
}
