<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * GodparentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GodparentRepository extends EntityRepository implements UserProviderInterface
{
    public function createPassword()
    {
        $chars = array_merge(range(0,9), range('a','z'),range('A', 'Z'));
        shuffle($chars);
        $password = '';
        for($i=0;$i<20;$i++){
            $password .= $chars[rand(0,61)];
        }
        return $password;
    }

    public function findOneByEmailOrUsername($username)
    {
        $qb = $this->createQueryBuilder('u')
            ->andWhere('u.username=:username OR u.email=:email')
            ->setParameter('username', $username)
            ->setParameter('email', $username);
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function loadUserByUsername($username)
    {
        $user = $this->findOneByEmailOrUsername($username);
        if(!$user){
            throw new UsernameNotFoundException();
        }
        return $user;
    }

    public function refreshUser(UserInterface $user)
    {
        $class = get_class($user);
        if(!$this->supportsClass($class)){
            throw new UnsupportedUserException();
        }
        if(null === $user = $this->find($user->getId())){
            throw new UsernameNotFoundException();
        }
        return $user;
    }

    public function supportsClass($class)
    {
        return $this->getEntityName() === $class || is_subclass_of($class, $this->getEntityName());
    }
}
