<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GodparentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GodparentRepository extends EntityRepository
{
    public function createPassword()
    {
        $chars = array_merge(range(0,9), range('a','z'),range('A', 'Z'));
        shuffle($chars);
        $password = '';
        for($i=0;$i<20;$i++){
            $password .= $chars[rand(0,61)];
        }
        return $password;
    }
}
