<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageStaticRepository extends EntityRepository
{
    public function findZooPages()
    {
        $q = $this->_em->createQuery('SELECT p FROM ZPB\AdminBundle\Entity\PageStatic p JOIN ZPB\AdminBundle\Entity\PostTarget t WHERE t.slug=:slug');
        $q->setParameter('slug', 'zooparc-de-beauval');
        return $q->getResult();
    }
}
