<?php

namespace ZPB\AdminBundle\Entity;

use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends SortableRepository
{
    public function getLastPositionInCategory($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->join('ZPB\AdminBundle\Entity\PhotoCategory', 'c')->where('c.id=:cid')
            ->setParameter('cid', $id)
            ->select('MAX(p.position)');
        $result = $qb->getQuery()->getSingleScalarResult();
        if($result !== null){
            $result = intval($result);
        }
        return $result;

    }
}
