<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function publish(Post $post, $dbSave = false)
    {
        $post->setIsPublished(true)->setIsDropped(false)->setIsArchived(false)->setIsDraft(false);
        $post->setPublishedAt(new \DateTime())->setDroppedAt(null)->setArchivedAt(null);
        $this->_em->persist($post);
        if ($dbSave) {
            $this->_em->flush();
        }
    }

    public function drop(Post $post, $dbSave = false)
    {
        $post->setIsPublished(false)->setIsDropped(true)->setIsArchived(false)->setIsDraft(false);
        $post->setPublishedAt(null)->setDroppedAt(new \DateTime())->setArchivedAt(null);
        $this->_em->persist($post);
        if ($dbSave) {
            $this->_em->flush();
        }
    }

    public function archive(Post $post, $dbSave = false)
    {
        $post->setIsPublished(false)->setIsDropped(false)->setIsArchived(true)->setIsDraft(false);
        $post->setPublishedAt(null)->setDroppedAt(null)->setArchivedAt(new \DateTime());
        $this->_em->persist($post);
        if ($dbSave) {
            $this->_em->flush();
        }
    }

    public function setFrontOf(post $post, PostTarget $target)
    {
        $target->setFrontPostId($post->getLongId());
    }


    public function getPublished(PostTarget $target = null)
    {
        $q = $this->_em->createQuery(
            'SELECT p FROM ZPB\AdminBundle\Entity\Post p JOIN ZPB\AdminBundle\Entity\PostTarget t WHERE p.isPublished=:isPublished AND t.slug=:slug ORDER BY p.publishedAt DESC'
        );
        $q->setParameter('isPublished', true);
        $q->setParameter('slug', $target->getSlug());

        return $q->getResult();

    }


}
