<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getDrafts()
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.isPublished = :isPublished')
            ->andWhere('p.isArchived = :isArchived')
            ->setParameter('isPublished', false)
            ->setParameter('isArchived', false)
            ->orderBy('p.createdAt', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function getPublished()
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.isPublished = :isPublished')
            ->andWhere('p.isArchived = :isArchived')
            ->setParameter('isPublished', true)
            ->setParameter('isArchived', false)
            ->orderBy('p.createdAt', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function getArchived()
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.isPublished = :isPublished')
            ->andWhere('p.isArchived = :isArchived')
            ->setParameter('isPublished', false)
            ->setParameter('isArchived', true)
            ->orderBy('p.createdAt', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
