<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostTagRepository extends EntityRepository
{
    public function getByTarget($target)
    {
        $qb = $this->createQueryBuilder('t')->where('t.target = :target')->orderBy('t.name', 'DESC');
        $qb->setParameter('target', $target);
        return $qb->getQuery()->getResult();
    }
}
