<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCategoryRepository extends EntityRepository
{
    public function getByTarget($target)
    {
        $qb = $this->createQueryBuilder('c')->where('c.target = :target')->orderBy('c.name', 'DESC');
        $qb->setParameter('target', $target);
        return $qb->getQuery()->getResult();
    }
}
