<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublishedPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublishedPostRepository extends EntityRepository
{
    public function getByTarget($target)
    {
        $qb = $this->createQueryBuilder('p')->where('p.target= :target')->andWhere('p.isArchived := isArchived')->orderBy('p.publishedAt', 'ASC');
        $qb->setParameter('target', $target)->setParameter('isArchived',false);
        return $qb->getQuery()->getResult();
    }
}
