parameters:
#    zpb_sites_hotels.example.class: ZPB\Sites\HotelsBundle\Example

services:
#    zpb_sites_hotels.example:
#        class: %zpb_sites_hotels.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
