imports:
    - { resource: config.yml }
framework:
    router:
        resource: "%kernel.root_dir%/config/routing_mobile_zoo.yml"
mobile_detect:
    redirect:
        mobile:
            is_enabled: false
        tablet:
            is_enabled: false
        full:
            is_enabled: false
    switch_device_view: ~
