imports:
    - { resource: config.yml }
framework:
    router:
        resource: "%kernel.root_dir%/config/routing_mobile_zoo.yml"
mobile_detect:
    redirect:
        mobile:
            is_enabled: false
        tablet:
            is_enabled: false
        full:
            is_enabled: true
            host: https://new.zoobeauval.com
            action: redirect_without_path
    switch_device_view: ~
