zpb_sites_common:
    resource: "@ZPBSitesCommonBundle/Resources/config/routing.yml"
    prefix:   /

zpb_sites_hotels:
    resource: "@ZPBSitesHotelsBundle/Resources/config/routing.yml"
    prefix:   /
    host: "new.leshotelsdebeauval.com"
    schemes: ["https"]


zpb_sites_ce:
    resource: "@ZPBSitesCEBundle/Resources/config/routing.yml"
    prefix:   /
    host: "new.ce.zoobeauval.com"
    schemes: ["https"]

zpb_sites_scolar:
    resource: "@ZPBSitesScolarBundle/Resources/config/routing.yml"
    prefix:   /
    host: "new.scolaires.zoobeauval.com"
    schemes: ["https"]

zpb_sites_group:
    resource: "@ZPBSitesGroupBundle/Resources/config/routing.yml"
    prefix:   /
    host: "new.groupes.zoobeauval.com"
    schemes: ["https"]

zpb_sites_pro:
    resource: "@ZPBSitesProBundle/Resources/config/routing.yml"
    prefix:   /
    host: "new.pro.zoobeauval.com"
    schemes: ["https"]

zpb_sites_bn:
    resource: "@ZPBSitesBNBundle/Resources/config/routing.yml"
    prefix:   /
    host: "new.beauvalnature.com"
    schemes: ["https"]

zpb_sites_zoo:
    resource: "@ZPBSitesZooBundle/Resources/config/routing.yml"
    prefix:   /
    host: "new.zoobeauval.com"
    schemes: ["https"]

zpb_admin:
    resource: "@ZPBAdminBundle/Resources/config/routing.yml"
    prefix:   /
    host: "new.admin.zooparc.com"
    schemes: ["https"]

