security:
    encoders:
        ZPB\AdminBundle\Entity\AdminUser:
            algorithm: sha512
            encode_as_base64: true
            iterations: 7000

        ZPB\AdminBundle\Entity\Godparent:
            algorithm: sha512
            encode_as_base64: true
            iterations: 7000

    providers:
        adminuser_provider:
            entity:
                class: ZPBAdminBundle:AdminUser
        sponsorship_provider:
            entity:
                class: ZPBAdminBundle:Godparent
                #property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPERADMIN: [ROLE_USER, ROLE_ADMIN]

    access_control:
        #- { host: ^(new\.|www\.)?admin\.zooparc\.com$, path: ^/, requires_channel: https, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        #- { host: ^(new\.|www\.)?admin\.zooparc\.com$, path: ^/, requires_channel: https, roles: [ROLE_USER]}
        #- { host: ^(new\.|www\.)?admin\.zooparc\.com$, path: ^/utilisateurs, requires_channel: https, roles: ROLE_SUPERADMIN }
        #- { host: ^(new\.|www\.)?admin\.zooparc\.com$, path: ^/utilisateur/.+, requires_channel: https, roles: ROLE_SUPERADMIN }
        - { host: ^(new\.|www\.)?admin\.zooparc\.com$, path: ^/(?!(login|login_check|logout)/?$), requires_channel: https, roles: ROLE_USER }

        - { host: ^(new\.|www\.)?zoobeauval\.com$, path: ^/parrainages/mon-compte.*, requires_channel: https, roles: ROLE_GODPARENT }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        sponsorship:
            host: ^(new\.|www\.)?zoobeauval\.com$
            pattern: ^/parrainages
            security: true
            provider: sponsorship_provider
            access_denied_url: /
            anonymous: ~
            form_login:
                login_path: /parrainages/login
                check_path: /parrainages/login_check
                csrf_provider: form.csrf_provider
            logout:
                path: /parrainages/logout
                target: /

        administration:
            host: ^(new\.|www\.)?admin.zooparc\.com$
            pattern: ^/
            security: true
            provider: adminuser_provider
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_provider: form.csrf_provider
            logout:
                path: /logout
                target: /

        default:
            anonymous: ~
