zpb_sites_zoo_homepage:
    path:     /
    defaults: { _controller: ZPBSitesZooBundle:Index:index }
    methods: ["GET"]

zpb_sites_zoo_parrainages_routes:
    prefix: /parrainages
    resource: "@ZPBSitesZooBundle/Resources/config/routing/parrainages.yml"
