zpb_sites_zoo_homepage:
    path:     /
    defaults: { _controller: ZPBSitesZooBundle:Index:index }
    methods: ["GET"]

zpb_sites_zoo_faq:
    path:     /faq
    defaults: { _controller: ZPBSitesZooBundle:FAQ:index }
    methods: ["GET"]



zpb_sites_zoo_download_image:
    path: /telecharger/image/{filename}
    defaults: { _controller: ZPBSitesZooBundle:Download:downloadImage }
    methods: ["GET"]
    requirements:
        filename: ".+"

zpb_sites_zoo_download_pdf:
    path: /telecharger/image/{filename}
    defaults: { _controller: ZPBSitesZooBundle:Download:downloadPdf }
    methods: ["GET"]
    requirements:
        filename: ".+"

zpb_sites_zoo_parrainages_routes:
    prefix: /parrainages
    resource: "@ZPBSitesZooBundle/Resources/config/routing/parrainages.yml"

zpb_sites_zoo_actualites_routes:
    prefix: /actualites
    resource: "@ZPBSitesZooBundle/Resources/config/routing/actualite.yml"

zpb_sites_zoo_phototheque_routes:
    prefix: /phototheque
    resource: "@ZPBSitesZooBundle/Resources/config/routing/phototheque.yml"
