zpb_sites_zoo_testpage:
    path: /test
    defaults: { _controller: ZPBSitesZooBundle:TestDesign:index }


zpb_sites_zoo_homepage:
    path:     /
    defaults: { _controller: ZPBSitesZooBundle:Index:index }
    methods: ["GET"]

zpb_sites_zoo_faq:
    path:     /faq
    defaults: { _controller: ZPBSitesZooBundle:FAQ:index }
    methods: ["GET"]

zpb_sites_zoo_contact:
    path:     /contact
    defaults: { _controller: ZPBSitesZooBundle:Contact:index }
    methods: ["GET","POST"]

zpb_sites_zoo_cgv:
    path: /conditions-generales-de-vente
    defaults: { _controller: ZPBSitesZooBundle:CGV:index }
    methods: ["GET"]

zpb_sites_zoo_legales:
    path: /mentions-legales
    defaults: { _controller: ZPBSitesZooBundle:Legales:index }
    methods: ["GET"]

zpb_sites_zoo_download_image:
    path: /telecharger/image/{filename}
    defaults: { _controller: ZPBSitesZooBundle:Download:downloadImage }
    methods: ["GET"]
    requirements:
        filename: ".+"

zpb_sites_zoo_download_image_hd:
    path: /telecharger/image/{filename}
    defaults: { _controller: ZPBSitesZooBundle:Download:downloadHDImage }
    methods: ["GET"]
    requirements:
        filename: ".+"

zpb_sites_zoo_download_pdf:
    path: /telecharger/pdf/{filename}
    defaults: { _controller: ZPBSitesZooBundle:Download:downloadPdf }
    methods: ["GET"]
    requirements:
        filename: ".+"

zpb_sites_zoo_parrainages_routes:
    prefix: /parrainages
    resource: "@ZPBSitesZooBundle/Resources/config/routing/parrainages.yml"

zpb_sites_zoo_actualites_routes:
    prefix: /actualites
    resource: "@ZPBSitesZooBundle/Resources/config/routing/actualite.yml"

zpb_sites_zoo_phototheque_routes:
    prefix: /galerie-photo
    resource: "@ZPBSitesZooBundle/Resources/config/routing/phototheque.yml"


zpb_sites_zoo_pratique_routes:
    prefix: /pratique
    resource: "@ZPBSitesZooBundle/Resources/config/routing/pratique.yml"

zpb_sites_zoo_pedagogie_routes:
    prefix: /pedagogie
    resource: "@ZPBSitesZooBundle/Resources/config/routing/pedagogie.yml"

zpb_sites_zoo_zooparc_routes:
    prefix: /zooparc
    resource: "@ZPBSitesZooBundle/Resources/config/routing/zooparc.yml"

zpb_sites_zoo_newsletter_routes:
    prefix: /newsletter
    resource: "@ZPBSitesZooBundle/Resources/config/routing/newsletter.yml"

zpb_sites_zoo_presse_routes:
    prefix: /presse
    resource: "@ZPBSitesZooBundle/Resources/config/routing/presse.yml"

zpb_sites_zoo_reseaux_sociaux_routes:
    prefix: /reseaux-sociaux
    resource: "@ZPBSitesZooBundle/Resources/config/routing/reseaux_sociaux.yml"
