parameters:
#    zpb_sites_pro.example.class: ZPB\Sites\ProBundle\Example

services:
#    zpb_sites_pro.example:
#        class: %zpb_sites_pro.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
