<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function publish(Post $post, $dbSave = false)
    {
        $post->setIsPublished(true)->setIsDropped(false)->setIsArchived(false)->setIsDraft(false);
        $post->setPublishedAt(new \DateTime())->setDroppedAt(null)->setArchivedAt(null);
        $this->_em->persist($post);
        if ($dbSave) {
            $this->_em->flush();
        }
    }

    public function drop(Post $post, $dbSave = false)
    {
        $post->setIsPublished(false)->setIsDropped(true)->setIsArchived(false)->setIsDraft(false);
        $post->setPublishedAt(null)->setDroppedAt(new \DateTime())->setArchivedAt(null);
        $this->_em->persist($post);
        if ($dbSave) {
            $this->_em->flush();
        }
    }

    public function archive(Post $post, $dbSave = false)
    {
        $post->setIsPublished(false)->setIsDropped(false)->setIsArchived(true)->setIsDraft(false);
        $post->setPublishedAt(null)->setDroppedAt(null)->setArchivedAt(new \DateTime());
        $this->_em->persist($post);
        if ($dbSave) {
            $this->_em->flush();
        }
    }

    public function setFrontOf(post $post, PostTarget $target)
    {
        $target->setFrontPostId($post->getLongId());
    }


    public function getPublished(PostTarget $target = null)
    {
        $q = $this->_em->createQuery(
            'SELECT p FROM ZPB\AdminBundle\Entity\Post p  JOIN p.targets t WHERE p.isPublished=:isPublished AND t.slug=:slug ORDER BY p.publishedAt DESC'
        );
        $q->setParameter('isPublished', true);
        $q->setParameter('slug', $target->getSlug());

        return $q->getResult();

    }

    public function getCategoriesByTarget($target)
    {
        $sql = "SELECT * FROM zpb_post_categories AS c WHERE c.id IN (SELECT DISTINCT p.category_id FROM zpb_posts AS p WHERE p.id IN (SELECT pt.post_id FROM zpb_posts_targets AS pt WHERE pt.posttarget_id = :id))";
        $rsm = new ResultSetMappingBuilder($this->_em);
        $rsm->addRootEntityFromClassMetadata('ZPB\AdminBundle\Entity\PostCategory', 'c');
        $query = $this->_em->createNativeQuery($sql, $rsm);
        $query->setParameter('id', $target->getId());
        return $query->getResult();
    }

    public function getTagsByTarget($target)
    {
        $sql = "SELECT * FROM zpb_post_tags AS t WHERE t.id IN (SELECT DISTINCT p.posttag_id FROM zpb_posts_tags AS p WHERE p.post_id IN (SELECT pt.post_id FROM zpb_posts_targets AS pt WHERE pt.posttarget_id = 1))";
        $rsm = new ResultSetMappingBuilder($this->_em);
        $rsm->addRootEntityFromClassMetadata('ZPB\AdminBundle\Entity\PostTag', 't');
        $query = $this->_em->createNativeQuery($sql, $rsm);
        $query->setParameter('id', $target->getId());
        return $query->getResult();
    }

    public function getPublishedByCategoryAndTarget($category, $target)
    {
        $q = $this->_em->createQuery(
'SELECT p FROM ZPB\AdminBundle\Entity\Post p JOIN p.category c JOIN p.targets t  WHERE p.isPublished=:isPublished AND t.slug=:slug AND c.id=:id ORDER BY p.publishedAt DESC'
        );
        $q->setParameter('isPublished', true);
        $q->setParameter('slug', $target->getSlug());
        $q->setParameter('id', $category->getId());

        return $q->getResult();
    }

    public function getPublishedByTagAndTarget($tag, $target)
    {
        $q = $this->_em->createQuery(
            'SELECT p FROM ZPB\AdminBundle\Entity\Post p JOIN p.tags tag JOIN p.targets t  WHERE p.isPublished=:isPublished AND t.slug=:slug AND tag.id=:id ORDER BY p.publishedAt DESC'
        );
        $q->setParameter('isPublished', true);
        $q->setParameter('slug', $target->getSlug());
        $q->setParameter('id', $tag->getId());

        return $q->getResult();
    }

}
