zpb_admin_test:
    path: /test
    defaults: { _controller: ZPBAdminBundle:Base:test }
    methods: ["GET"]

zpb_admin_homepage:
    path:     /
    defaults: { _controller: ZPBAdminBundle:Index:index }
    methods: ["GET"]

zpb_admin_posts_routes:
    prefix: /actualites
    resource: "@ZPBAdminBundle/Resources/config/routing/posts.yml"

zpb_admin_users_routes:
    prefix: /utilisateurs
    resource: "@ZPBAdminBundle/Resources/config/routing/users.yml"

zpb_admin_photos_routes:
    prefix: /photos
    resource: "@ZPBAdminBundle/Resources/config/routing/photos.yml"

zpb_admin_photos_categories_routes:
    prefix: /categories-photos
    resource: "@ZPBAdminBundle/Resources/config/routing/photo_categories.yml"

zpb_admin_photos_animations_routes:
    prefix: /animations
    resource: "@ZPBAdminBundle/Resources/config/routing/animations.yml"

zpb_admin_photos_animations_days_routes:
    prefix: /animations/journees
    resource: "@ZPBAdminBundle/Resources/config/routing/animations_days.yml"

zpb_admin_parrainages_routes:
    prefix: /parrainages
    resource: "@ZPBAdminBundle/Resources/config/routing/sponsorings.yml"

zpb_admin_posts_categories_routes:
    prefix: /actualites/categories
    resource: "@ZPBAdminBundle/Resources/config/routing/posts_categories.yml"

zpb_admin_posts_tags_routes:
    prefix: /actualites/mots-cles
    resource: "@ZPBAdminBundle/Resources/config/routing/posts_tags.yml"

zpb_admin_faq_routes:
    prefix: /faq
    resource: "@ZPBAdminBundle/Resources/config/routing/faq.yml"

zpb_admin_mediatheque_routes:
    prefix: /mediatheque
    resource: "@ZPBAdminBundle/Resources/config/routing/mediatheque.yml"

zpb_admin_institutions_routes:
    prefix: /institutions
    resource: "@ZPBAdminBundle/Resources/config/routing/institutions.yml"


zpb_admin_xhrs_routes:
    prefix: /xhr
    resource: "@ZPBAdminBundle/Resources/config/routing/xhr.yml"

zpb_admin_zoo_static_pages_routes:
    prefix: /zoo/pages-statiques
    resource: "@ZPBAdminBundle/Resources/config/routing/zoo_static_pages.yml"
