parameters:
#    zpb_admin.example.class: ZPB\AdminBundle\Example

services:
#    zpb_admin.example:
#        class: %zpb_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
