zpb_sites_ce_english_index:
    path: /
    defaults: { _controller: ZPBSitesCEBundle:English/Index:index }
    methods: ["GET"]

zpb_sites_ce_english_faq:
    path:     /faq
    defaults: { _controller: ZPBSitesCEBundle:English/FAQ:index }
    methods: ["GET"]

zpb_sites_ce_english_contact:
    path: /contact
    defaults: { _controller: ZPBSitesCEBundle:English/Contact:index }
    methods: ["GET", "POST"]



