parameters:
#    zpb_sites_group.example.class: ZPB\Sites\GroupBundle\Example

services:
#    zpb_sites_group.example:
#        class: %zpb_sites_group.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
