parameters:
#    zpb_sites_bn.example.class: ZPB\Sites\BNBundle\Example

services:
#    zpb_sites_bn.example:
#        class: %zpb_sites_bn.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
