zpb_sites_zoo_actualites_homepage:
    path: /{page}
    defaults: { _controller: ZPBSitesZooBundle:Actualite:index, page: 1}
    methods: ["GET"]
    requirements:
        page: \d+

zpb_sites_zoo_actualites_single:
    path: /{slug}
    defaults: { _controller:  ZPBSitesZooBundle:Actualite:single }
    methods: ["GET"]
    requirements:
        slug: "^[a-zA-Z0-9_-]+$"
