zpb_sites_zoo_parrainages_homepage:
    path:     /
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:index }
    methods: ["GET"]

zpb_sites_zoo_parrainages_animal_show:
    path: /decouvrir/{name}
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:showAnimal }
    methods: ["GET"]
    requirements:
        name: "[a-zA-Z0-9_-]+"

zpb_sites_zoo_parrainages_add_to_basket:
    path: /ajouter-au-panier
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:addSponsoringToBasket }
    methods: ["POST"]

zpb_sites_zoo_parrainages_add_recipient:
    path: /enregistrer-beneficiaire
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:addRecipient }
    methods: ["GET","POST"]

zpb_sites_zoo_parrainages_show_basket:
    path: /mon-panier
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:showBasket }
    methods: ["GET"]

zpb_sites_zoo_parrainage_remove_from_basket:
    path: /supprimer-du-panier/{id}
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:removeSponsoringFromBasket }
    methods: ["GET"]
    requirements:
        id: "[0-9-]+"

zpb_sites_zoo_parrainages_login_or_register:
    path: /identification
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:loginOrRegister}
    methods: ["GET"]

#zpb_sites_zoo_parrainages_payment_register:
#    path: /nouveau-parrain
#    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:register }
#    methods: ["POST"]

zpb_sites_zoo_parrainages_payment_recap:
    path: /recapitulatif
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:recapOrderAfterLogin }
    methods: ["GET"]

zpb_sites_zoo_parrainages_login:
    path: /login
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Account:login }
    methods: ["GET"]

zpb_sites_zoo_parrainages_login_check:
    path: /login_check
    methods: ["POST"]

zpb_sites_zoo_parrainages_logout:
    path: /logout
    methods: ["GET"]

zpb_sites_zoo_parrainage_my_account:
    path: /mon-compte
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Account:myAccount }
    methods: ["GET","POST"]

zpb_sites_zoo_parrainages_lost_password:
    path: /demande-identifiants
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Account:lostPassword }
    methods: ["GET", "POST"]

zpb_sites_zoo_parrainages_revalidate:
    path: /nouveaux-identifiants
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Account:activationLink }
    methods: ["GET"]

zpb_sites_zoo_parrainages_payer_cb:
    path: /paiement/carte-bancaire
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:paiementCB }
    methods: ["GET"]


