zpb_sites_zoo_parrainages_homepage:
    path:     /
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:index }
    methods: ["GET"]

zpb_sites_zoo_parrainages_animal_show:
    path: /decouvrir/{name}
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:showAnimal }
    methods: ["GET"]
    requirements:
        name: "[a-zA-Z0-9_-]+"

zpb_sites_zoo_parrainages_add_to_basket:
    path: /ajouter-au-panier
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:addSponsoringToBasket }
    methods: ["POST"]

zpb_sites_zoo_parrainages_show_basket:
    path: /mon-panier
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:showBasket }
    methods: ["GET"]

zpb_sites_zoo_parrainage_remove_from_basket:
    path: /supprimer-du-panier/{id}
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:removeSponsoringFromBasket }
    methods: ["GET"]
    requirements:
        id: "[0-9-]+"

zpb_sites_zoo_parrainages_login_or_register:
    path: /identification
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:loginOrRegister }
    methods: ["GET"]

zpb_sites_zoo_parrainages_payment_register:
    path: /nouveau-parrain
    defaults: { _controller: ZPBSitesZooBundle:Parrainage/Index:register }
    methods: ["POST"]
