zpb_sites_zoo_phototheque_hd_index:
    path: /
    defaults: { _controller: ZPBSitesZooBundle:PhotothequeHd/PhotoHd:index }
    methods: ["GET"]

zpb_sites_zoo_phototheque_hd_show_category:
    path: /{institutslug}/{catslug}
    defaults: { _controller: ZPBSitesZooBundle:PhotothequeHd/PhotoHd:showCategory }
    methods: ["GET"]
    requirements:
        institutslug: "[a-zA-Z_-]+"
        catslug: "[a-zA-Z_-]+"
