zpb_sites_zoo_pratique_tarifs_horaires:
    path: /horaires-tarifs
    defaults: { _controller: ZPBSitesZooBundle:Pratique:tarifsHoraires }
    methods: ["GET"]

zpb_sites_zoo_pratique_acces:
    path: /acces
    defaults: { _controller: ZPBSitesZooBundle:Pratique:acces }
    methods: ["GET"]

zpb_sites_zoo_pratique_animations:
    path: /au-programme
    defaults: { _controller: ZPBSitesZooBundle:Pratique:animations }
    methods: ["GET"]

zpb_sites_zoo_pratique_map:
    path: /plan-de-visite
    defaults: { _controller: ZPBSitesZooBundle:Pratique:map }
    methods: ["GET"]

zpb_sites_zoo_pratique_resto:
    path: /restauration
    defaults: { _controller: ZPBSitesZooBundle:Pratique:resto }
    methods: ["GET"]

zpb_sites_zoo_pratique_services:
    path: /services
    defaults: { _controller: ZPBSitesZooBundle:Pratique:services }
    methods: ["GET"]


zpb_sites_zoo_api_info_anim:
    path: /api/animation/{year}/{month}/{day}
    defaults: { _controller: ZPBSitesZooBundle:Pratique:apiInfoAnim }
    methods: ["GET"]
    requirements:
        year: "20(0[0-9]|[1-9][0-9])"
        month: "[1-9]|1[0-2]"
        day: "[1-9]|1[0-9]|2[0-9]|3[0-1]"



