parameters:
#    zpb_sites_scolar.example.class: ZPB\Sites\ScolarBundle\Example

services:
#    zpb_sites_scolar.example:
#        class: %zpb_sites_scolar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
