parameters:
#    zpb_sites_common.example.class: ZPB\Sites\CommonBundle\Example

services:
#    zpb_sites_common.example:
#        class: %zpb_sites_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
